FROM php:8.3-fpm

RUN apt-get update && apt-get install -y \
    git \
    curl \
    zip \
    unzip \
    libpq-dev \
    libsnmp-dev \
    snmp \
    && docker-php-ext-install pdo pdo_pgsql snmp

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www